[build]
builder = "NIXPACKS"

[deploy]
startCommand = "npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "backend"
source = "backend"

[services.variables]
NODE_ENV = "production"
PORT = "${{ RAILWAY_PORT }}"
DATABASE_PATH = "/app/data/database.sqlite"
CORS_ORIGINS = "${{ FRONTEND_URL }}"

[[services.volumes]]
name = "database"
mountPath = "/app/data"